### ISSUE TITLE
segfault on jigsaw puzzle

### ISSUE THREAD

**Issue by andimeier** [andimeier/sudokusolver#26]
I get a segfault when trying to solve this jigsaw puzzle:

```
type: jigsaw
640030071
007000400
090000020
000080000
003000100
000090000
020000050
006000200
970050082
shapes:
111112222
131311434
333344442
353666422
356676444
557776668
577978888
579979998
555999888
```

This is causing the segfault:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000100406c6a in initContainers () at src/sudoku/grid.c:329
329                     int *containerIndexes = field->containerIndexes[set];
(gdb) bt
#0  0x0000000100406c6a in initContainers () at src/sudoku/grid.c:329
#1  0x00000001004066de in setupGrid () at src/sudoku/grid.c:144
#2  0x000000010040652b in setupSudoku (_parameters=0x100411ec0 <parameters>) at src/sudoku/sudoku.c:33
#3  0x000000010040118d in main (argc=2, argv=0xffffcbe0) at src/main.c:72
(gdb)

```

**Comment by andimeier** [comment]
Reasons: shapes are incorrectly defined, e.g. shape 2 has only 7 fields while shapes 3 and 4 have 10 fields each.

=> missing validation check for containers. Every container must contain of exactly MAX_NUMBER fields
